#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jul 26 16:35:10 IST 2026
maven-metadata-sonatype-snapshots.xml.lastUpdated=1785063910004
maven-metadata-OSGEO.xml.lastUpdated=1785063910003
maven-metadata-osgeo.xml.error=
maven-metadata-central.xml.lastUpdated=1785063909994
maven-metadata-OSGEO.xml.error=
maven-metadata-sonatype-snapshots.xml.error=
maven-metadata-osgeo.xml.lastUpdated=1785063909978
